### ISSUE TITLE
responsive: keep item aspect ratio on narrow viewports

### ISSUE THREAD

**Issue by pacien** [ldgallery/ldgallery#105]
Items are squished instead of being properly resized on narrow viewports: the aspect ratio of the elements should be preserved!

![15811791038916](https://user-images.githubusercontent.com/1449319/74088558-01913780-4a98-11ea-81cc-23b67e8d77cc.png)

**Comment by OzoneGrif** [comment]
I've been using it for a bit, and actually like it. It's like a preview while changing the filters.
There's a small aspect ratio issue on the main view, but I'm not sure if we should fix it. Our thumbnails are just too large by default.

**Comment by pacien** [comment]
> I've been using it for a bit, and actually like it. It's like a preview while changing the filters.

Indeed, the preview of the result of the filter query is nice to have on mobile too.
We should keep the current size of the sidebar on mobile devices.


> There's a small aspect ratio issue on the main view, but I'm not sure if we should fix it.

That's the subject of the issue. The aspect ratio of the pictures still needs to be preserved in any case. It is plain wrong to squish pictures horizontally while keeping their vertical dimension the same, in particular for pictures of people and their faces. The same is true the other way.

Just consider this example with your current GitHub profile picture:

![15815087094383](https://user-images.githubusercontent.com/1449319/74333055-71a10580-4d97-11ea-9d11-2baf7ba38e46.png)


> Our thumbnails are just too large by default.

The generated thumbnails will always be too big for this particular case as they're tailored for the expanded view. Generating two sets of thumbnails of different sizes is counter-productive as both will end up being loaded when the panel is collapsed, making the bandwidth usage worse. It should however be enough to let the browser downsize the picture again in this case with some additional lines of CSS.

**Comment by pacien** [comment]
This is actually not affecting only narrow viewports, but also standard desktop resolutions: panoramic pictures are also displayed without their proper ratio even on larger screens.

The `flex`-powered image grid doesn't seem _flexible_ enough to allow items to be resized to fit a slot while keeping the correct aspect ratio. We might need to find another way to generate this grid properly. There's probably a component for that somewhere that would also properly handle lazy DOM creation (#112).
