### ISSUE TITLE
performance: loading of big collections freezes the viewer

### ISSUE THREAD

**Issue by pacien** [ldgallery/ldgallery#112]
Opening a big directory or displaying the search results yielding to a large collection of items makes the viewer unresponsive for some time.

The issue starts to become noticeable starting from ~1000 items on desktop and with as few as ~100 items on mobile devices.

Debugging indicates that this is due to the creation of the DOM elements.
It doesn't seem possible to display any loading indicator during these loading times.

The solution could be to use a component handling the partial rendering of the collection, recycling DOM elements. as the user scrolls.

**Comment by OzoneGrif** [comment]
True, this will be done after v1.0
This is not a bug, it's a feature, or you could use a tag "performance"
