### ISSUE TITLE
viewer: use CSS modules

### ISSUE THREAD

**Issue by pacien** [ldgallery/ldgallery#196]
CSS is currently not scoped in components. Consider using CSS modules or any other way of adding some scoping.

We need to consider both the isolation between our internal components, for which CSS modules would help, and external overridability which is prevented by the random prefixes added in CSS modules.

* https://github.com/css-modules/css-modules
* https://vue-loader.vuejs.org/guide/css-modules.html
* https://vue-loader.vuejs.org/guide/scoped-css.html

**Comment by zeroinformatique** [comment]
Waiting for #284 to be closed and merged.
