### ISSUE TITLE
viewer: switch to Vue 3

### ISSUE THREAD

**Issue by pacien** [ldgallery/ldgallery#217]
It'll probably be released in Q2 2020 and will bring a lot of improvements. Even though it's currently in beta, we can afford giving it a try.

**Comment by zeroinformatique** [comment]
I did a test this week-end and managed to get Vue 3, Router and VueX to work properly.
There are a few minor syntax changes in Vue 3, but nothing major and it should be quick to upgrade.
VueX changed slightly more, maybe we should remove this library when upgrading; it's not really necessary for Ld.
