### ISSUE TITLE
viewer: tag propositions do not take the subtraction operator into account

### ISSUE THREAD

**Issue by zeroinformatique** [ldgallery/ldgallery#220]
Add a tag, then substract another tag, the proposition list offers both tags instead of only the first one minus the second one.

**Comment by pacien** [comment]
Minimum Reproducible Example in the branch `mre_only_subtraction_shows_others`.

**Comment by pacien** [comment]
Could not reproduce in ldgallery v2.2. This might have been solved in a previous version. Closing.
