### ISSUE TITLE
gui: framework study

### ISSUE THREAD

**Issue by zeroinformatique** [ldgallery/ldgallery#264]

**Comment by zeroinformatique** [comment]
Considered frameworks:
- [JavaFX / OpenJFX](https://openjfx.io/)
- [.NET Mono](https://www.mono-project.com/)
- [Nuklear](https://github.com/Immediate-Mode-UI/Nuklear)
- [Muon](https://github.com/ImVexed/muon)
- [Revery](https://www.outrunlabs.com/revery/)

**Comment by zeroinformatique** [comment]
First, quick analyse:
- OpenJFX is under the GPLv2 licence, the GUI will requires a JVM in order to run. OpenJDK 11 includes a [packager](https://walczak.it/blog/distributing-javafx-desktop-applications-without-requiring-jvm-using-jlink-and-jpackage) so, this shouldn't be an issue.
- .NET Mono is under the MIT licence, it uses GTK+ (not a fan)
- Nuklear is under the MIT licence, it's a lightweight C library with multiple wrappers. GoLang or Rust could be interesting to test.
- Muon is under the MIT licence, it's a lightweight GoLang library based on [UltraLight](https://ultralig.ht/). UltraLight has its own ["FREE" licence](https://github.com/ultralight-ux/Ultralight/blob/master/license/LICENSE.txt).
- Revery is under the MIT licence, it's based on [Reason](https://reasonml.github.io/) and inspired by React.

**Comment by zeroinformatique** [comment]
**Revery**:
I installed Revery on my computer. Following the documentation was easy, although the information are spread between the [revery GitHub](https://github.com/revery-ui/revery), the [revery-quick-start GitHub](https://github.com/revery-ui/revery-quick-start), and its [requirements for building Revery](https://github.com/revery-ui/revery/wiki/Building-&-Installing) page.

On Windows, you must install *NodeJS* (12.18.4 here), then with npm: *esy* and *windows-build-tools*
Finally, you can `esy install` and `esy build`: it will take more than an hour and require a lot of RAM.

You can run the app with `esy run`.
The executable file *App.exe* won't work unless you copy some DLLs:
- libEGL.dll
- libGLESv2.dll
- libwinpthread-1.dll
- SDL2.dll
- skia.dll

I'm not certain about other DLLs since the [packager](https://github.com/revery-ui/revery-packager) didn't work for me (it's 12 months old).

**Comment by zeroinformatique** [comment]
**neutralino.js**:
Easy and light to install, build and run with NodeJS. There's a feeling it's not mature technology: The firewall is triggered when opening the application for the first time (instead of using the local-loop to avoid this), and there's no hot-reload during development.

The API is very limited but would be enough for our needs, except you can't pipe the stdout of your command to the JavaScript; meaning you have to wait for the command to end to get the result. Not really what I would hope to during compilation.

**Comment by zeroinformatique** [comment]
**OpenJFX**:
Relatively easy to install and build, slightly harder to run and package (but nothing tremendous). You need OpenJDK and OpenJFX, and environment variables configured, and Java in your path. You also need https://wixtoolset.org/ to generate the installer. I used these commands to package a simple HelloFX app:

```
javac --module-path %PATH_TO_FX% --add-modules javafx.controls,javafx.fxml HelloFX.java
jlink --module-path %PATH_TO_FX% --add-modules javafx.controls,javafx.fxml --output ./dist
mkdir input
jar -c HelloFX.class > ./input/hello.jar
jpackage --name HelloFX --input input --main-jar hello.jar --main-class HelloFX.class --runtime-image dist/
```

The result is an installer (exe) weighting 32mb, and about 85mb when installed. It was clean, the uninstaller was created automatically. One could argue that it's heavy to package a whole JRE for such a small tool.

**Comment by zeroinformatique** [comment]
**Flutter**:
The development stack is very heavy and complex; if you want to create an app for Android and iOS, you will need the appropriate tooling and emulators (or a plugged phone); this can be installed along with Android Studio or manually. Flutter offers a lot of helpers to check if everything works fine and to fix it. I used the following commands during my installation:
- `flutter doctor`
- `flutter config --android-sdk C:\Programming\android-sdk`
- `flutter doctor --android-licenses`
- `flutter devices`
- `flutter channel dev`
- `flutter upgrade`
- `flutter config --enable-windows-desktop`

On Windows, you have to install Visual Studio 2019 and the Development for C++ tooling to generate the Desktop APP. The tooling is different on Linux and MacOS. Flutter automatically detects when VS is installed.

I used Visual Studio Code + the Flutter extension as IDE, but you can also use Android Studio with its own Flutter extension.
Everything worked properly, with no issue. So far, this is the best candidate.

**Comment by pacien** [comment]
Another interesting GUI toolkit we can look at is V UI for the V programming language: https://github.com/vlang/ui.
It's declarative and the generated binaries seem to be lightweight.

**Comment by pacien** [comment]
There's also a bunch of native and external GUI toolkits for Nim: https://matthiashager.com/gui-options-for-nim

**Comment by pacien** [comment]
(Posting this a bit late as a note which can still be useful for other
projects).

---

[Eto] is an interesting C# cross-platform framework which bridges to native
desktop toolkits, resulting in applications which do not stand out in their
environment.

The generated applications are single-file binaries without external
dependencies. Currently, targetting Windows requires building on Windows.

[Eto]: https://github.com/picoe/Eto

---

There is also Microsoft's [.NET Multi-platform App UI][MAUI], still in preview
phase.

[MAUI]: https://github.com/dotnet/maui
