### ISSUE TITLE
viewer: unify icon bounding boxes

### ISSUE THREAD

**Issue by pacien** [ldgallery/ldgallery#267]
Currently, icons are aligned "by hand" everywhere they're used in the viewer because they're not properly aligned by default and often have different dimensions. This is very tedious and often results in misaligned icons with improper hit boxes.

Let's try solving this globally by enforcing some standard alignment with normalised square bounding boxes.

**Comment by zeroinformatique** [comment]
I suggest switching to MDI, which are more normalized than FontAwesome.
