### ISSUE TITLE
viewer: initial zoom level not always properly set

### ISSUE THREAD

**Issue by pacien** [ldgallery/ldgallery#268]
The initial zoom level when viewing pictures item isn't always properly set when navigating from one picture to another by modifying the URL anchor.

It's possible that we're computing the initial zoom level only when mounting the component, which only happens when coming from another view but not when loading another picture while staying in the same view.

**Comment by pacien** [comment]
To reproduce:
* create two picture items with different dimensions and aspect ratios, that we'll name `A.jpg` and `B.jpg`,
* open the viewer, navigate to and open `A.jpg`,
* _the initial zoom level is properly set to fit the image in the viewport,_
* without going back to the thumbnail grid view, alter the anchor to point to `#/B.jpg`,
* __observe that the zoom isn't re-initialised properly to fit this new image in the viewport.__

This is particularly annoying when navigating through sequences of pictures with internal links in their description for example.

**Comment by pacien** [comment]
According to @zeroinformatique, we just need to add a watcher for the item prop in addition to the mount event.

**Comment by zeroinformatique** [comment]
You will also have to uninstall the current `LdZoom` controller. There's no uninstall method, so you'll have to create one.

**Comment by pacien** [comment]
The "slow loading" is also not triggered on URL change.
It would perhaps be better to destroy and remount the whole LdPicture component when the item changes.
