### ISSUE TITLE
viewer: optional user-defined markdown splash screen

### ISSUE THREAD

**Issue by pacien** [ldgallery/ldgallery#284]
As annoying as splash screens might be on most websites, they can still be desirable for some users to display arbitrary information to (newcoming) visitors of their gallery.

Note that this differs from simply putting a "readme.md" file in the gallery in the sense that the document will be harder to miss, as it would be displayed even when the user lands on a particular resource in the gallery through a specific link.

Example use cases:
* displaying a welcome message explaining the subject of the gallery and the specific groups of tags,
* displaying content warnings or legal copyright information,
* displaying links to the parent website and related resources,
* and so on...

Simply rendering and displaying some user-defined Markdown document would cover all those cases quite easily.

This splash screen should probably be added as a modal overlay. I'm not sure whether it's necessary to let the user add arbitrary action buttons, as regular links in the markdown document are probably already enough.

An "about" icon could additionally be added somewhere in the interface to show this screen again after its initial dismissal.

**Comment by zeroinformatique** [comment]
1- The config.yaml points to an optional "spashscreen" MarkDown file in the gallery
2- When the gallery opens, it displays this markdown fullscreen, centered, with a OK button to close it.
3- The markdown is hashed and stored on the client to avoid opening it again, unless the file changes.

There are no other buttons, and no other configuration.
The gallery won't display until the splash is closed.
