### ISSUE TITLE
compiler: rename to "generator"

### ISSUE THREAD

**Issue by pacien** [ldgallery/ldgallery#295]
The term "compiler" sounds weird and incorrect to non-technical and technical users alike.

It could be better to rename the differrent components of the ldgallery set of programs as follows:
* ldgallery viewer: the web viewer interface
* ldgallery generator (formerly compiler): the command line program allowing to generate the static gallery
* ldgallery editor (formerly GUI Tool): the future graphical user interface allowing editing the gallery

It was originally named like that instead of "generator" to avoid overlapping with another tool which would create a gallery template structure from scratch. This should instead be implemented as a sub-command of either the generator of the editor programs.

Renaming the component would have close to no impact on users ~~because there's no user anyway~~: the binaries, interfaces and packages stay the same. Only the names in the source repository and the documentation would need to be changed.

**Comment by zeroinformatique** [comment]
It's the right time to change name since Ld isn't heavily used.
I wouldn't mind **generator**, some alternatives for thoughts: 
**factory**, **producer**, **emitter**, **maker**, **builder**

I kinda like **builder** myself.

**Comment by pacien** [comment]
The current naming has the merit of being unambiguous.
Let's stick with it.
